services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data

  mongo:
    ports:
      - "27017:27017"
    volumes:
      - dev-mongo-data:/data/db

  prolog:
    ports:
      - "5001:5001"

  oem_backend:
    environment:
      MONGODB_URI: "mongodb://dbadmin:password123!@mongo:27017/oemdb?authSource=admin"
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./oem_backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

volumes:
  dev-postgres-data:
  dev-mongo-data:
