// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortManagement.Infrastructure.Data;

#nullable disable

namespace PortManagement.Infrastructure.Migrations
{
    [DbContext(typeof(PortManagementDbContext))]
    partial class PortManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DockStorageArea", b =>
                {
                    b.Property<Guid>("ServedDocksId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StorageAreaId")
                        .HasColumnType("uuid");

                    b.HasKey("ServedDocksId", "StorageAreaId");

                    b.HasIndex("StorageAreaId");

                    b.ToTable("StorageAreaDocks", (string)null);
                });

            modelBuilder.Entity("DockVesselTypes", b =>
                {
                    b.Property<Guid>("DockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VesselTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("DockId", "VesselTypeId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("DockVesselTypes", (string)null);
                });

            modelBuilder.Entity("PortManagement.Domain.Auth.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivationToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ActivationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IamUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActivationToken");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IamUserId")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("PortManagement.Domain.Auth.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedUser")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AffectedUser");

                    b.HasIndex("EventType");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("PortManagement.Domain.Auth.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoleName")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PortManagement.Domain.Docks.Entities.Dock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaxDraft")
                        .HasColumnType("integer");

                    b.Property<int>("MaxSTS")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Docks");
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.PhysicalResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("_requiredQualificationIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RequiredQualificationIds");

                    b.HasKey("Id");

                    b.ToTable("PhysicalResources");

                    b.HasDiscriminator<string>("ResourceType").HasValue("PhysicalResource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PortManagement.Domain.Privacy.PrivacyPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PrivacyPolicies");
                });

            modelBuilder.Entity("PortManagement.Domain.Privacy.UserPolicyView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserPolicyViews");
                });

            modelBuilder.Entity("PortManagement.Domain.Qualification.Entities.Qualification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("PortManagement.Domain.ShippingAgent.Entities.ShippingAgentOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AlternativeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ShippingAgentOrganizations");
                });

            modelBuilder.Entity("PortManagement.Domain.ShippingAgent.Entities.ShippingAgentRepresentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShippingAgentOrganizationId")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAgentOrganizationId");

                    b.ToTable("ShippingAgentRepresentatives");
                });

            modelBuilder.Entity("PortManagement.Domain.Staff.Entities.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("_qualificationIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("QualificationIds");

                    b.HasKey("Id");

                    b.ToTable("StaffMembers", (string)null);
                });

            modelBuilder.Entity("PortManagement.Domain.Storage.Entities.StorageArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.CargoManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VesselVisitNotificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("CargoManifests");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.ContainerInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bay")
                        .HasColumnType("integer");

                    b.Property<Guid>("CargoManifestId")
                        .HasColumnType("uuid");

                    b.Property<string>("CargoType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ContainerId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CargoManifestId");

                    b.ToTable("ContainerInfos");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.CrewInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaptainName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CrewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CrewInfos");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.CrewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CitizenId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CrewInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CrewInfoId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.VesselRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Imo")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VesselTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Imo")
                        .IsUnique();

                    b.HasIndex("VesselTypeId");

                    b.ToTable("VesselRecords");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.VesselType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityTEU")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxBays")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRows")
                        .HasColumnType("integer");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("VesselVisitNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByOfficerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedDockId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CrewId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ETD")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByOfficerId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ShippingAgentRepresentativeId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VesselId")
                        .HasColumnType("uuid");

                    b.Property<string>("_businessId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("BusinessId");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDockId");

                    b.HasIndex("CrewId");

                    b.HasIndex("ShippingAgentRepresentativeId");

                    b.HasIndex("VesselId");

                    b.HasIndex("_businessId")
                        .IsUnique()
                        .HasDatabaseName("IX_VesselVisitNotification_BusinessId");

                    b.ToTable("VesselVisitNotifications");
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.STSCrane", b =>
                {
                    b.HasBaseType("PortManagement.Domain.PhysicalResources.Entities.PhysicalResource");

                    b.Property<Guid?>("DockId")
                        .HasColumnType("uuid");

                    b.HasIndex("DockId");

                    b.HasDiscriminator().HasValue("STSCrane");
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.Truck", b =>
                {
                    b.HasBaseType("PortManagement.Domain.PhysicalResources.Entities.PhysicalResource");

                    b.HasDiscriminator().HasValue("Truck");
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.YardCrane", b =>
                {
                    b.HasBaseType("PortManagement.Domain.PhysicalResources.Entities.PhysicalResource");

                    b.HasDiscriminator().HasValue("YardCrane");
                });

            modelBuilder.Entity("DockStorageArea", b =>
                {
                    b.HasOne("PortManagement.Domain.Docks.Entities.Dock", null)
                        .WithMany()
                        .HasForeignKey("ServedDocksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortManagement.Domain.Storage.Entities.StorageArea", null)
                        .WithMany()
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DockVesselTypes", b =>
                {
                    b.HasOne("PortManagement.Domain.Docks.Entities.Dock", null)
                        .WithMany()
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortManagement.Domain.Vessel.Entities.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.Auth.UserRole", b =>
                {
                    b.HasOne("PortManagement.Domain.Auth.AppUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.PhysicalResource", b =>
                {
                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRArea", "Area", b1 =>
                        {
                            b1.Property<Guid>("PhysicalResourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("Area");

                            b1.HasKey("PhysicalResourceId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalResourceId");
                        });

                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("PhysicalResourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Code");

                            b1.HasKey("PhysicalResourceId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalResourceId");
                        });

                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("PhysicalResourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Description");

                            b1.HasKey("PhysicalResourceId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalResourceId");
                        });

                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PROperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<Guid>("PhysicalResourceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("OperationalWindow");

                            b1.HasKey("PhysicalResourceId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalResourceId");
                        });

                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRSetupTime", "SetupTime", b1 =>
                        {
                            b1.Property<Guid>("PhysicalResourceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer")
                                .HasColumnName("SetupTimeMinutes");

                            b1.HasKey("PhysicalResourceId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("PhysicalResourceId");
                        });

                    b.Navigation("Area")
                        .IsRequired();

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("OperationalWindow")
                        .IsRequired();

                    b.Navigation("SetupTime")
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.Qualification.Entities.Qualification", b =>
                {
                    b.OwnsOne("PortManagement.Domain.Qualification.ValueObjects.QCode", "Code", b1 =>
                        {
                            b1.Property<Guid>("QualificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("Code");

                            b1.HasKey("QualificationId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Qualifications");

                            b1.WithOwner()
                                .HasForeignKey("QualificationId");
                        });

                    b.OwnsOne("PortManagement.Domain.Qualification.ValueObjects.QDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("QualificationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("Description");

                            b1.HasKey("QualificationId");

                            b1.ToTable("Qualifications");

                            b1.WithOwner()
                                .HasForeignKey("QualificationId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.ShippingAgent.Entities.ShippingAgentRepresentative", b =>
                {
                    b.HasOne("PortManagement.Domain.ShippingAgent.Entities.ShippingAgentOrganization", "ShippingAgentOrganization")
                        .WithMany("Representatives")
                        .HasForeignKey("ShippingAgentOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingAgentOrganization");
                });

            modelBuilder.Entity("PortManagement.Domain.Staff.Entities.StaffMember", b =>
                {
                    b.OwnsOne("PortManagement.Domain.Staff.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("Email");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("PortManagement.Domain.Staff.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("PortManagement.Domain.Staff.ValueObjects.SMId", "StaffMemberId", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("StaffMemberId");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("PortManagement.Domain.Staff.ValueObjects.SMName", "ShortName", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ShortName");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("PortManagement.Domain.Staff.ValueObjects.SMOperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<Guid>("StaffMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("OperationalWindow");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMembers");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("OperationalWindow")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("ShortName")
                        .IsRequired();

                    b.Navigation("StaffMemberId")
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.CargoManifest", b =>
                {
                    b.HasOne("VesselVisitNotification", null)
                        .WithMany("CargoManifests")
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.ContainerInfo", b =>
                {
                    b.HasOne("PortManagement.Domain.Vessel.Entities.CargoManifest", "CargoManifest")
                        .WithMany("Containers")
                        .HasForeignKey("CargoManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoManifest");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.CrewMember", b =>
                {
                    b.HasOne("PortManagement.Domain.Vessel.Entities.CrewInfo", null)
                        .WithMany("SafetyOfficers")
                        .HasForeignKey("CrewInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.VesselRecord", b =>
                {
                    b.HasOne("PortManagement.Domain.Vessel.Entities.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("VesselVisitNotification", b =>
                {
                    b.HasOne("PortManagement.Domain.Docks.Entities.Dock", "AssignedDock")
                        .WithMany()
                        .HasForeignKey("AssignedDockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PortManagement.Domain.Vessel.Entities.CrewInfo", "Crew")
                        .WithMany()
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PortManagement.Domain.ShippingAgent.Entities.ShippingAgentRepresentative", "ShippingAgentRepresentative")
                        .WithMany()
                        .HasForeignKey("ShippingAgentRepresentativeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortManagement.Domain.Vessel.Entities.VesselRecord", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedDock");

                    b.Navigation("Crew");

                    b.Navigation("ShippingAgentRepresentative");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.STSCrane", b =>
                {
                    b.HasOne("PortManagement.Domain.Docks.Entities.Dock", null)
                        .WithMany("STSCranes")
                        .HasForeignKey("DockId");

                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("STSCraneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CapacityUnit");

                            b1.Property<double>("Value")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(20)
                                .HasColumnType("double precision")
                                .HasColumnName("CapacityValue");

                            b1.HasKey("STSCraneId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("STSCraneId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.Truck", b =>
                {
                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CapacityUnit");

                            b1.Property<double>("Value")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(20)
                                .HasColumnType("double precision")
                                .HasColumnName("CapacityValue");

                            b1.HasKey("TruckId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("TruckId");
                        });

                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRSpeed", "Speed", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("SpeedUnit");

                            b1.Property<double>("Value")
                                .HasMaxLength(20)
                                .HasColumnType("double precision")
                                .HasColumnName("SpeedValue");

                            b1.HasKey("TruckId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("TruckId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("Speed")
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.PhysicalResources.Entities.YardCrane", b =>
                {
                    b.OwnsOne("PortManagement.Domain.PhysicalResources.ValueObjects.PRCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("YardCraneId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("CapacityUnit");

                            b1.Property<double>("Value")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasMaxLength(20)
                                .HasColumnType("double precision")
                                .HasColumnName("CapacityValue");

                            b1.HasKey("YardCraneId");

                            b1.ToTable("PhysicalResources");

                            b1.WithOwner()
                                .HasForeignKey("YardCraneId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();
                });

            modelBuilder.Entity("PortManagement.Domain.Auth.AppUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("PortManagement.Domain.Docks.Entities.Dock", b =>
                {
                    b.Navigation("STSCranes");
                });

            modelBuilder.Entity("PortManagement.Domain.ShippingAgent.Entities.ShippingAgentOrganization", b =>
                {
                    b.Navigation("Representatives");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.CargoManifest", b =>
                {
                    b.Navigation("Containers");
                });

            modelBuilder.Entity("PortManagement.Domain.Vessel.Entities.CrewInfo", b =>
                {
                    b.Navigation("SafetyOfficers");
                });

            modelBuilder.Entity("VesselVisitNotification", b =>
                {
                    b.Navigation("CargoManifests");
                });
#pragma warning restore 612, 618
        }
    }
}
