@startuml
title Level 2 Sequence Diagram (SD) - UPDATE User Story
autonumber

actor ":Port Authority Officer" as PAO
participant ":Visualization (UI)" as UI
participant ":Port Management" as POB

PAO -> UI: asks to update a resource
activate UI

    UI -> POB: request available resources
    activate POB
    POB -->> UI: available resources
    deactivate POB

    UI -->> PAO: show available resources

    PAO -> UI: selected the resource
    activate UI

        UI -->> PAO: asks to insert the necessary data
        
        PAO -> UI: inserts data
        
        UI -> POB: request the update of resource
        activate POB
        POB -->> UI: resource updated / error in data
        deactivate POB
    
    UI -->> PAO: resource updated / error in data
    deactivate UI

deactivate UI

@enduml
